### ISSUE TITLE
"Login Failed, known issues: "The words you typed in didn't match the picture""

### ISSUE THREAD

**Issue by popeeyy** [sentanos/roblox-js#82]
Whenever I try to log in, I keep getting that a CAPTCHA is being failed. My bot won't even log in now. Is there a fix to get past this or something?

**Comment by sentanos** [comment]
This is a restriction by Roblox because you were logging in too many times in a row and there is no way to bypass it through the bot directly. Either way a few hours for the restriction to go away or use a different IP through a VPN or proxy. If you really need to get in now you can login manually through a browser and copy the .ROBLOSECURITY cookie and then put it into the script's cookie jar manually with 
```javascript
rbx.options.jar=`PASTE COOKIE HERE`.
```

**Comment by popeeyy** [comment]
I tried that multiple times and it still says that the picture didn't match the words.

**Comment by sentanos** [comment]
Tried what multiple times?

**Comment by popeeyy** [comment]
rbx.options.jar=`mycookie`

**Comment by sentanos** [comment]
My mistake, the code is actually `rbx.options.jar.session=cookie`

**Comment by popeeyy** [comment]
I'm still receiving this error.

**Comment by sentanos** [comment]
Please show all the code you are using.

**Comment by popeeyy** [comment]
https://hastebin.com/zizipacive.js

**Comment by sentanos** [comment]
Once you set the cookie you do not use `rbx.login`.

**Comment by popeeyy** [comment]
Oh, okay.

**Comment by efewqefwfd** [comment]
![image](https://user-images.githubusercontent.com/29686338/34643430-637bf860-f2e1-11e7-8848-707e486e3315.png)

**Comment by sentanos** [comment]
1. That is your login cookie, you should do log out of all sessions to prevent people from hacking your account.
2. You are obviously misunderstanding how to use the module. Please grasp the concept of node.js promises and how to program before attempting to use this.
